server:
  address: 127.0.0.1
  port: 9760
  servlet:
    session:
      timeout: 30m

spring:
  profiles:
    active: dev
  application:
    name: stresspilot
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB

application:
  mode: desktop

  cors:
    allowed-origins:
      - "localhost:3000"

  message:
    batch-size: 1000
    flush-interval-ms: 1000
    websocket:
      enabled: true
      push-interval-ms: 500
      max-per-push: 2000
      topic: /topic/logs
    kafka:
      enabled: false
      topic: stresspilot.request-logs
      bootstrap-servers: localhost:9092


management:
  endpoints:
    web:
      exposure:
        include: "health,shutdown"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      show-details: always