services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Viettel!VDS
      - POSTGRES_DB=stresspilot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - stresspilot

  redis:
    image: redis:8.6.0
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass "Viettel!VDS"
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - stresspilot

volumes:
  postgres_data:
  redis_data:

networks:
  stresspilot: