CREATE TABLE configs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    config_key   VARCHAR(255) NOT NULL,
    config_value TEXT,
    CONSTRAINT pk_configs PRIMARY KEY (id),
    CONSTRAINT uc_configs_config_key UNIQUE (config_key)
);

CREATE TABLE environments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT pk_environments PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    name           VARCHAR(255) NOT NULL,
    description    TEXT,
    environment_id BIGINT       NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id),
    CONSTRAINT fk_projects_on_environment FOREIGN KEY (environment_id) REFERENCES environments (id)
);

CREATE TABLE endpoints
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    name              VARCHAR(255) NOT NULL,
    description       TEXT,
    type              VARCHAR(20)  NOT NULL,
    project_id        BIGINT       NOT NULL,
    url               VARCHAR(255),
    body              TEXT,
    success_condition TEXT,
    http_method       VARCHAR(10),
    http_headers      TEXT,
    http_parameters   TEXT,
    grpc_service_name VARCHAR(255),
    grpc_method_name  VARCHAR(255),
    grpc_stub_path    TEXT,
    CONSTRAINT pk_endpoints PRIMARY KEY (id),
    CONSTRAINT fk_endpoints_on_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE environment_variables
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    environment_id BIGINT       NOT NULL,
    key            VARCHAR(255) NOT NULL,
    value          TEXT,
    is_active      BOOLEAN      NOT NULL,
    CONSTRAINT pk_environment_variables PRIMARY KEY (id),
    CONSTRAINT uc_environment_variables_environment_key UNIQUE (environment_id, key),
    CONSTRAINT fk_environment_variables_on_environment FOREIGN KEY (environment_id) REFERENCES environments (id)
);

CREATE TABLE flows
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    project_id  BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    type        VARCHAR(255) NOT NULL,
    CONSTRAINT pk_flows PRIMARY KEY (id),
    CONSTRAINT fk_flows_on_project FOREIGN KEY (project_id) REFERENCES projects (id)
);

CREATE TABLE flow_steps
(
    id             VARCHAR(36) NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    flow_id        BIGINT      NOT NULL,
    type           VARCHAR(10) NOT NULL,
    endpoint_id    BIGINT,
    pre_processor  TEXT,
    post_processor TEXT,
    next_if_true   VARCHAR(255),
    next_if_false  VARCHAR(255),
    condition      TEXT,
    CONSTRAINT pk_flow_steps PRIMARY KEY (id),
    CONSTRAINT fk_flow_steps_on_endpoint FOREIGN KEY (endpoint_id) REFERENCES endpoints (id),
    CONSTRAINT fk_flow_steps_on_flow FOREIGN KEY (flow_id) REFERENCES flows (id)
);

CREATE TABLE functions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    name        VARCHAR(100) NOT NULL,
    body        TEXT         NOT NULL,
    description VARCHAR(500),
    is_active   BOOLEAN      NOT NULL,
    CONSTRAINT pk_functions PRIMARY KEY (id),
    CONSTRAINT uc_functions_name UNIQUE (name)
);

CREATE TABLE runs
(
    id               VARCHAR(20) NOT NULL,
    flow_id          BIGINT      NOT NULL,
    status           VARCHAR(10) NOT NULL,
    threads          INTEGER     NOT NULL,
    duration         INTEGER     NOT NULL,
    ramp_up_duration INTEGER     NOT NULL,
    started_at       TIMESTAMP   NOT NULL,
    completed_at     TIMESTAMP,
    CONSTRAINT pk_runs PRIMARY KEY (id),
    CONSTRAINT fk_runs_on_flow FOREIGN KEY (flow_id) REFERENCES flows (id)
);

CREATE TABLE request_logs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id        VARCHAR(20) NOT NULL,
    endpoint_id   BIGINT      NOT NULL,
    status_code   INTEGER     NOT NULL,
    is_success    BOOLEAN     NOT NULL,
    response_time BIGINT      NOT NULL,
    request       TEXT,
    response      TEXT,
    created_at    TIMESTAMP   NOT NULL,
    CONSTRAINT pk_request_logs PRIMARY KEY (id),
    CONSTRAINT fk_request_logs_on_endpoint FOREIGN KEY (endpoint_id) REFERENCES endpoints (id),
    CONSTRAINT fk_request_logs_on_run FOREIGN KEY (run_id) REFERENCES runs (id)
);

CREATE TABLE schedules
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flow_id     BIGINT       NOT NULL,
    quartz_expr VARCHAR(255) NOT NULL,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    threads     INTEGER      NOT NULL DEFAULT 1,
    duration    INTEGER      NOT NULL DEFAULT 60,
    ramp_up     INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMP    NOT NULL,
    updated_at  TIMESTAMP    NOT NULL,
    CONSTRAINT pk_schedules PRIMARY KEY (id),
    CONSTRAINT fk_schedules_flow FOREIGN KEY (flow_id) REFERENCES flows (id) ON DELETE CASCADE
);

CREATE TABLE runs_snapshot
(
    id               VARCHAR(20) NOT NULL,
    flow_id          BIGINT      NOT NULL,
    status           VARCHAR(10) NOT NULL,
    threads          INTEGER     NOT NULL,
    duration         INTEGER     NOT NULL,
    ramp_up_duration INTEGER     NOT NULL,
    started_at       TIMESTAMP   NOT NULL,
    completed_at     TIMESTAMP   NOT NULL,
    metrics          TEXT        NOT NULL,
    created_at       TIMESTAMP   NOT NULL,
    CONSTRAINT pk_runs_snapshot PRIMARY KEY (id)
);
