CREATE TABLE custom_report_sheets
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255) NOT NULL,
    display_order INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT pk_custom_report_sheets PRIMARY KEY (id)
);

CREATE TABLE custom_report_elements
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sheet_id      BIGINT       NOT NULL,
    name          VARCHAR(255) NOT NULL,
    type          VARCHAR(10)  NOT NULL,
    config        TEXT,
    display_order INT          NOT NULL DEFAULT 0,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    CONSTRAINT pk_custom_report_elements PRIMARY KEY (id),
    CONSTRAINT fk_elements_sheet FOREIGN KEY (sheet_id)
        REFERENCES custom_report_sheets (id) ON DELETE CASCADE
);
