CREATE TABLE configs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    config_key   VARCHAR(255) NOT NULL,
    config_value TEXT,
    CONSTRAINT pk_configs PRIMARY KEY (id)
);

CREATE TABLE endpoints
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    name              VARCHAR(255) NOT NULL,
    description       TEXT,
    type              VARCHAR(20)  NOT NULL,
    project_id        BIGINT       NOT NULL,
    url               VARCHAR(255),
    body              TEXT,
    success_condition TEXT,
    http_method       VARCHAR(10),
    http_headers      TEXT,
    http_parameters   TEXT,
    grpc_service_name VARCHAR(255),
    grpc_method_name  VARCHAR(255),
    grpc_stub_path    TEXT,
    CONSTRAINT pk_endpoints PRIMARY KEY (id)
);

CREATE TABLE environment_variables
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    environment_id BIGINT       NOT NULL,
    key            VARCHAR(255) NOT NULL,
    value          TEXT,
    is_active      BOOLEAN      NOT NULL,
    CONSTRAINT pk_environment_variables PRIMARY KEY (id)
);

CREATE TABLE environments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_environments PRIMARY KEY (id)
);

CREATE TABLE flow_steps
(
    id             VARCHAR(36) NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    flow_id        BIGINT      NOT NULL,
    type           VARCHAR(10) NOT NULL,
    endpoint_id    BIGINT,
    pre_processor  TEXT,
    post_processor TEXT,
    next_if_true   VARCHAR(255),
    next_if_false  VARCHAR(255),
    condition      TEXT,
    CONSTRAINT pk_flow_steps PRIMARY KEY (id)
);

CREATE TABLE flows
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    project_id  BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    CONSTRAINT pk_flows PRIMARY KEY (id)
);

CREATE TABLE projects
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    name           VARCHAR(255) NOT NULL,
    description    TEXT,
    environment_id BIGINT       NOT NULL,
    CONSTRAINT pk_projects PRIMARY KEY (id)
);

CREATE TABLE request_logs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    run_id        BIGINT                      NOT NULL,
    endpoint_id   BIGINT                      NOT NULL,
    status_code   INTEGER                     NOT NULL,
    is_success    BOOLEAN                     NOT NULL,
    response_time BIGINT                      NOT NULL,
    request       TEXT,
    response      TEXT,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_request_logs PRIMARY KEY (id)
);

CREATE TABLE runs
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    flow_id          BIGINT                      NOT NULL,
    status           VARCHAR(10)                 NOT NULL,
    threads          INTEGER                     NOT NULL,
    duration         INTEGER                     NOT NULL,
    ramp_up_duration INTEGER                     NOT NULL,
    started_at       TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    completed_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_runs PRIMARY KEY (id)
);

ALTER TABLE environment_variables
    ADD CONSTRAINT uc_2e64ec9f3bcb663bf5dad176e UNIQUE (environment_id, key);

ALTER TABLE configs
    ADD CONSTRAINT uc_configs_config_key UNIQUE (config_key);

ALTER TABLE endpoints
    ADD CONSTRAINT FK_ENDPOINTS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE environment_variables
    ADD CONSTRAINT FK_ENVIRONMENT_VARIABLES_ON_ENVIRONMENT FOREIGN KEY (environment_id) REFERENCES environments (id);

ALTER TABLE flows
    ADD CONSTRAINT FK_FLOWS_ON_PROJECT FOREIGN KEY (project_id) REFERENCES projects (id);

ALTER TABLE flow_steps
    ADD CONSTRAINT FK_FLOW_STEPS_ON_ENDPOINT FOREIGN KEY (endpoint_id) REFERENCES endpoints (id);

ALTER TABLE flow_steps
    ADD CONSTRAINT FK_FLOW_STEPS_ON_FLOW FOREIGN KEY (flow_id) REFERENCES flows (id);

ALTER TABLE projects
    ADD CONSTRAINT FK_PROJECTS_ON_ENVIRONMENT FOREIGN KEY (environment_id) REFERENCES environments (id);

ALTER TABLE request_logs
    ADD CONSTRAINT FK_REQUEST_LOGS_ON_ENDPOINT FOREIGN KEY (endpoint_id) REFERENCES endpoints (id);

ALTER TABLE request_logs
    ADD CONSTRAINT FK_REQUEST_LOGS_ON_RUN FOREIGN KEY (run_id) REFERENCES runs (id);

ALTER TABLE runs
    ADD CONSTRAINT FK_RUNS_ON_FLOW FOREIGN KEY (flow_id) REFERENCES flows (id);