INSERT INTO configs (id, config_key, config_value, created_at, updated_at)
VALUES (1, 'HTTP_CONNECT_TIMEOUT', '10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (2, 'HTTP_READ_TIMEOUT', '30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (3, 'HTTP_WRITE_TIMEOUT', '30', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (4, 'HTTP_MAX_POOL_SIZE', '100', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (5, 'HTTP_KEEP_ALIVE_DURATION', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (6, 'FLOW_ENDPOINT_STRICT_LINEAR', 'false', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (7, 'HTTP_PROXY_HOST', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (8, 'HTTP_PROXY_PORT', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (9, 'HTTP_PROXY_USERNAME', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       (10, 'HTTP_PROXY_PASSWORD', NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT (config_key) DO NOTHING;

SELECT setval(pg_get_serial_sequence('configs', 'id'), (SELECT MAX(id) FROM configs));