CREATE TABLE functions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    name        VARCHAR(100)                            NOT NULL,
    body        TEXT                                    NOT NULL,
    description VARCHAR(500),
    is_active   BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_functions PRIMARY KEY (id)
);

ALTER TABLE functions
    ADD CONSTRAINT uc_functions_name UNIQUE (name);